//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cletor.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Syncfusion_SfRichTextBoxAdv_WPF
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_SfRichTextBoxAdv_WPF()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion_SfRichTextBoxAdv_WPF_Designer", typeof(Syncfusion_SfRichTextBoxAdv_WPF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt Text.
        /// </summary>
        public static string AlternativeText
        {
            get
            {
                return ResourceManager.GetString("AlternativeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string ArabicList
        {
            get
            {
                return ResourceManager.GetString("ArabicList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least.
        /// </summary>
        public static string Atleast
        {
            get
            {
                return ResourceManager.GetString("Atleast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BordersShadingDialogAllBorder
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogAllBorder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply To.
        /// </summary>
        public static string BordersShadingDialogApplyTo
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogApplyTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Borders.
        /// </summary>
        public static string BordersShadingDialogBorders
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogBorders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string BordersShadingDialogBoxBorder
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogBoxBorder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string BordersShadingDialogColor
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string BordersShadingDialogCustomBorder
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogCustomBorder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string BordersShadingDialogFill
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogFill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BordersShadingDialogNoBorder
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogNoBorder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string BordersShadingDialogPreview
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string BordersShadingDialogSetting
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string BordersShadingDialogShading
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogShading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string BordersShadingDialogStyle
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Borders and Shading.
        /// </summary>
        public static string BordersShadingDialogTitle
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string BordersShadingDialogWidth
        {
            get
            {
                return ResourceManager.GetString("BordersShadingDialogWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string BottomAlignment
        {
            get
            {
                return ResourceManager.GetString("BottomAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string BottomMargin
        {
            get
            {
                return ResourceManager.GetString("BottomMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string BulletList
        {
            get
            {
                return ResourceManager.GetString("BulletList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Numbering and Bullets.
        /// </summary>
        public static string BulletsAndNumberingDialogTitle
        {
            get
            {
                return ResourceManager.GetString("BulletsAndNumberingDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell
        {
            get
            {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell Options.
        /// </summary>
        public static string CellOptionsDialogTitle
        {
            get
            {
                return ResourceManager.GetString("CellOptionsDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string CenteredAlignment
        {
            get
            {
                return ResourceManager.GetString("CenteredAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character
        {
            get
            {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to Dictionary.
        /// </summary>
        public static string ContextMenuAddToDictionary
        {
            get
            {
                return ResourceManager.GetString("ContextMenuAddToDictionary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AutoFit.
        /// </summary>
        public static string ContextMenuAutoFit
        {
            get
            {
                return ResourceManager.GetString("ContextMenuAutoFit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AutoFit to Contents.
        /// </summary>
        public static string ContextMenuAutoFitToContents
        {
            get
            {
                return ResourceManager.GetString("ContextMenuAutoFitToContents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AutoFit to Window.
        /// </summary>
        public static string ContextMenuAutoFitToWindow
        {
            get
            {
                return ResourceManager.GetString("ContextMenuAutoFitToWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        public static string ContextMenuComment
        {
            get
            {
                return ResourceManager.GetString("ContextMenuComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenuCopy
        {
            get
            {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy Hyperlink.
        /// </summary>
        public static string ContextMenuCopyHyperlink
        {
            get
            {
                return ResourceManager.GetString("ContextMenuCopyHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ContextMenuCut
        {
            get
            {
                return ResourceManager.GetString("ContextMenuCut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        public static string ContextMenuDeleteComment
        {
            get
            {
                return ResourceManager.GetString("ContextMenuDeleteComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Hyperlink.
        /// </summary>
        public static string ContextMenuEditHyperlink
        {
            get
            {
                return ResourceManager.GetString("ContextMenuEditHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fixed Column Width.
        /// </summary>
        public static string ContextMenuFixedColumnWidth
        {
            get
            {
                return ResourceManager.GetString("ContextMenuFixedColumnWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font....
        /// </summary>
        public static string ContextMenuFontDialog
        {
            get
            {
                return ResourceManager.GetString("ContextMenuFontDialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string ContextMenuHyperlink
        {
            get
            {
                return ResourceManager.GetString("ContextMenuHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        public static string ContextMenuIgnoreAll
        {
            get
            {
                return ResourceManager.GetString("ContextMenuIgnoreAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Columns to the Left.
        /// </summary>
        public static string ContextMenuInsertLeftColumn
        {
            get
            {
                return ResourceManager.GetString("ContextMenuInsertLeftColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Columns to the Right.
        /// </summary>
        public static string ContextMenuInsertRightColumn
        {
            get
            {
                return ResourceManager.GetString("ContextMenuInsertRightColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Rows Above.
        /// </summary>
        public static string ContextMenuInsertRowAbove
        {
            get
            {
                return ResourceManager.GetString("ContextMenuInsertRowAbove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Rows Below.
        /// </summary>
        public static string ContextMenuInsertRowBelow
        {
            get
            {
                return ResourceManager.GetString("ContextMenuInsertRowBelow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string ContextMenuInsertTable
        {
            get
            {
                return ResourceManager.GetString("ContextMenuInsertTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merge Cells.
        /// </summary>
        public static string ContextMenuMergeCell
        {
            get
            {
                return ResourceManager.GetString("ContextMenuMergeCell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Hyperlink.
        /// </summary>
        public static string ContextMenuOpenHyperlink
        {
            get
            {
                return ResourceManager.GetString("ContextMenuOpenHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paragraph....
        /// </summary>
        public static string ContextMenuParagraphDialog
        {
            get
            {
                return ResourceManager.GetString("ContextMenuParagraphDialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ContextMenuPaste
        {
            get
            {
                return ResourceManager.GetString("ContextMenuPaste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Hyperlink.
        /// </summary>
        public static string ContextMenuRemoveHyperlink
        {
            get
            {
                return ResourceManager.GetString("ContextMenuRemoveHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table Properties....
        /// </summary>
        public static string ContextMenuTableProperties
        {
            get
            {
                return ResourceManager.GetString("ContextMenuTableProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogBoxCancel
        {
            get
            {
                return ResourceManager.GetString("DialogBoxCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogBoxOk
        {
            get
            {
                return ResourceManager.GetString("DialogBoxOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string DialogBoxOptions
        {
            get
            {
                return ResourceManager.GetString("DialogBoxOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogCloseButtonToolTip
        {
            get
            {
                return ResourceManager.GetString("DialogCloseButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left-to-right.
        /// </summary>
        public static string DirectionLeftToRight
        {
            get
            {
                return ResourceManager.GetString("DirectionLeftToRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Righ-to-left.
        /// </summary>
        public static string DirectionRightToLeft
        {
            get
            {
                return ResourceManager.GetString("DirectionRightToLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exactly.
        /// </summary>
        public static string Exactly
        {
            get
            {
                return ResourceManager.GetString("Exactly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FarEast.
        /// </summary>
        public static string FarEastList
        {
            get
            {
                return ResourceManager.GetString("FarEastList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for..
        /// </summary>
        public static string FindReplaceDialogErrorMessage
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindReplaceDialogFind
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogFind", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindReplaceDialogFindNext
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogFindNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find what.
        /// </summary>
        public static string FindReplaceDialogFindText
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogFindText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string FindReplaceDialogLessOption
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogLessOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string FindReplaceDialogMatchCase
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogMatchCase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string FindReplaceDialogMoreOption
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogMoreOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use regular expression.
        /// </summary>
        public static string FindReplaceDialogRegularExpression
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogRegularExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string FindReplaceDialogReplace
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogReplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string FindReplaceDialogReplaceAll
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogReplaceAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string FindReplaceDialogReplaceText
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogReplaceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All done. We made .
        /// </summary>
        public static string FindReplaceDialogSuccessMessage1
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogSuccessMessage1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  replacement..
        /// </summary>
        public static string FindReplaceDialogSuccessMessage2
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogSuccessMessage2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindReplaceDialogTitle
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find whole words only.
        /// </summary>
        public static string FindReplaceDialogWholeWord
        {
            get
            {
                return ResourceManager.GetString("FindReplaceDialogWholeWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FollowNumberWithNone
        {
            get
            {
                return ResourceManager.GetString("FollowNumberWithNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string FollowNumberWithSpace
        {
            get
            {
                return ResourceManager.GetString("FollowNumberWithSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string FollowNumberWithTab
        {
            get
            {
                return ResourceManager.GetString("FollowNumberWithTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string FontDialogAutomaticColor
        {
            get
            {
                return ResourceManager.GetString("FontDialogAutomaticColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double strikethrough.
        /// </summary>
        public static string FontDialogDoubleStrikeThrough
        {
            get
            {
                return ResourceManager.GetString("FontDialogDoubleStrikeThrough", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string FontDialogEffects
        {
            get
            {
                return ResourceManager.GetString("FontDialogEffects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string FontDialogFontColor
        {
            get
            {
                return ResourceManager.GetString("FontDialogFontColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FontDialogFontSize
        {
            get
            {
                return ResourceManager.GetString("FontDialogFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        public static string FontDialogFontStyle
        {
            get
            {
                return ResourceManager.GetString("FontDialogFontStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontDialogFontText
        {
            get
            {
                return ResourceManager.GetString("FontDialogFontText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        public static string FontDialogNoFontColor
        {
            get
            {
                return ResourceManager.GetString("FontDialogNoFontColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string FontDialogNoUnderline
        {
            get
            {
                return ResourceManager.GetString("FontDialogNoUnderline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string FontDialogPreview
        {
            get
            {
                return ResourceManager.GetString("FontDialogPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string FontDialogStrikeThrough
        {
            get
            {
                return ResourceManager.GetString("FontDialogStrikeThrough", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string FontDialogSubscript
        {
            get
            {
                return ResourceManager.GetString("FontDialogSubscript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string FontDialogSuperscript
        {
            get
            {
                return ResourceManager.GetString("FontDialogSuperscript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontDialogTitle
        {
            get
            {
                return ResourceManager.GetString("FontDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string FontDialogUnderline
        {
            get
            {
                return ResourceManager.GetString("FontDialogUnderline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format
        {
            get
            {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 1.
        /// </summary>
        public static string Heading1
        {
            get
            {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 2.
        /// </summary>
        public static string Heading2
        {
            get
            {
                return ResourceManager.GetString("Heading2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 3.
        /// </summary>
        public static string Heading3
        {
            get
            {
                return ResourceManager.GetString("Heading3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 4.
        /// </summary>
        public static string Heading4
        {
            get
            {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 5.
        /// </summary>
        public static string Heading5
        {
            get
            {
                return ResourceManager.GetString("Heading5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading 6.
        /// </summary>
        public static string Heading6
        {
            get
            {
                return ResourceManager.GetString("Heading6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string HyperlinkDialogAddress
        {
            get
            {
                return ResourceManager.GetString("HyperlinkDialogAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text to Display.
        /// </summary>
        public static string HyperlinkDialogDisplayText
        {
            get
            {
                return ResourceManager.GetString("HyperlinkDialogDisplayText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Hyperlink.
        /// </summary>
        public static string HyperlinkDialogTitle
        {
            get
            {
                return ResourceManager.GetString("HyperlinkDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click to follow link.
        /// </summary>
        public static string HyperlinkToolTipContent
        {
            get
            {
                return ResourceManager.GetString("HyperlinkToolTipContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string JustifiedAlignment
        {
            get
            {
                return ResourceManager.GetString("JustifiedAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LeadingZero.
        /// </summary>
        public static string LeadingZeroList
        {
            get
            {
                return ResourceManager.GetString("LeadingZeroList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftAlignment
        {
            get
            {
                return ResourceManager.GetString("LeftAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftMargin
        {
            get
            {
                return ResourceManager.GetString("LeftMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atleast.
        /// </summary>
        public static string LineSpacingAtleast
        {
            get
            {
                return ResourceManager.GetString("LineSpacingAtleast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exactly.
        /// </summary>
        public static string LineSpacingExactly
        {
            get
            {
                return ResourceManager.GetString("LineSpacingExactly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string LineSpacingMultiple
        {
            get
            {
                return ResourceManager.GetString("LineSpacingMultiple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Linked (paragraph and character).
        /// </summary>
        public static string Linked
        {
            get
            {
                return ResourceManager.GetString("Linked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose Level to modify.
        /// </summary>
        public static string ListDialogChooseLevel
        {
            get
            {
                return ResourceManager.GetString("ListDialogChooseLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aligned at.
        /// </summary>
        public static string ListDialogFirstLineIndent
        {
            get
            {
                return ResourceManager.GetString("ListDialogFirstLineIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Formatting for number.
        /// </summary>
        public static string ListDialogFormattingNumber
        {
            get
            {
                return ResourceManager.GetString("ListDialogFormattingNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indents.
        /// </summary>
        public static string ListDialogIndents
        {
            get
            {
                return ResourceManager.GetString("ListDialogIndents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text indent at.
        /// </summary>
        public static string ListDialogLeftIndents
        {
            get
            {
                return ResourceManager.GetString("ListDialogLeftIndents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List Level.
        /// </summary>
        public static string ListDialogListLevel
        {
            get
            {
                return ResourceManager.GetString("ListDialogListLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Follow number with.
        /// </summary>
        public static string ListDialogNumberFollow
        {
            get
            {
                return ResourceManager.GetString("ListDialogNumberFollow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number Format.
        /// </summary>
        public static string ListDialogNumberFormat
        {
            get
            {
                return ResourceManager.GetString("ListDialogNumberFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number style for this level.
        /// </summary>
        public static string ListDialogNumberStyle
        {
            get
            {
                return ResourceManager.GetString("ListDialogNumberStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart by.
        /// </summary>
        public static string ListDialogRestart
        {
            get
            {
                return ResourceManager.GetString("ListDialogRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string ListDialogStartAt
        {
            get
            {
                return ResourceManager.GetString("ListDialogStartAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Define List.
        /// </summary>
        public static string ListDialogTitle
        {
            get
            {
                return ResourceManager.GetString("ListDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 8.
        /// </summary>
        public static string ListLevelEight
        {
            get
            {
                return ResourceManager.GetString("ListLevelEight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 5.
        /// </summary>
        public static string ListLevelFive
        {
            get
            {
                return ResourceManager.GetString("ListLevelFive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        public static string ListLevelFour
        {
            get
            {
                return ResourceManager.GetString("ListLevelFour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 9.
        /// </summary>
        public static string ListLevelNine
        {
            get
            {
                return ResourceManager.GetString("ListLevelNine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        public static string ListLevelOne
        {
            get
            {
                return ResourceManager.GetString("ListLevelOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 7.
        /// </summary>
        public static string ListLevelSeven
        {
            get
            {
                return ResourceManager.GetString("ListLevelSeven", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 6.
        /// </summary>
        public static string ListLevelSix
        {
            get
            {
                return ResourceManager.GetString("ListLevelSix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        public static string ListLevelThree
        {
            get
            {
                return ResourceManager.GetString("ListLevelThree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        public static string ListLevelTwo
        {
            get
            {
                return ResourceManager.GetString("ListLevelTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading page.
        /// </summary>
        public static string LoadingPage
        {
            get
            {
                return ResourceManager.GetString("LoadingPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LowLetter.
        /// </summary>
        public static string LowLetterList
        {
            get
            {
                return ResourceManager.GetString("LowLetterList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LowRoman.
        /// </summary>
        public static string LowRomanList
        {
            get
            {
                return ResourceManager.GetString("LowRomanList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string MiniToolBarAlignmentToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarAlignmentToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string MiniToolBarBlackHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBlackHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string MiniToolBarBlueHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBlueHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string MiniToolBarBoldToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBoldToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightGreen.
        /// </summary>
        public static string MiniToolBarBrightGreenHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBrightGreenHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bullet Library.
        /// </summary>
        public static string MiniToolBarBulletsHeader
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBulletsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        public static string MiniToolBarBulletToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarBulletToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DarkBlue.
        /// </summary>
        public static string MiniToolBarDarkBlueHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDarkBlueHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DarkRed.
        /// </summary>
        public static string MiniToolBarDarkRedHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDarkRedHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DarkYellow.
        /// </summary>
        public static string MiniToolBarDarkYelowHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDarkYelowHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decrease Font Size.
        /// </summary>
        public static string MiniToolBarDecreaseFontToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDecreaseFontToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MiniToolBarDeleteTable
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDeleteTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Columns.
        /// </summary>
        public static string MiniToolBarDeleteTableColumns
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDeleteTableColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Rows.
        /// </summary>
        public static string MiniToolBarDeleteTableRows
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDeleteTableRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Table.
        /// </summary>
        public static string MiniToolBarDeleteTableToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarDeleteTableToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string MiniToolBarFontColorToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarFontColorToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        public static string MiniToolBarFontSizeToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarFontSizeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string MiniToolBarFontToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarFontToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gray-25%.
        /// </summary>
        public static string MiniToolBarGray25HighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarGray25HighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gray-50%.
        /// </summary>
        public static string MiniToolBarGray50HighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarGray50HighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string MiniToolBarGreenHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarGreenHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Highlight Color.
        /// </summary>
        public static string MiniToolBarHighlightColorToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarHighlightColorToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Increase Font Size.
        /// </summary>
        public static string MiniToolBarIncreaseFontToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarIncreaseFontToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string MiniToolBarInsertTable
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Above.
        /// </summary>
        public static string MiniToolBarInsertTableAbove
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTableAbove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Below.
        /// </summary>
        public static string MiniToolBarInsertTableBelow
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTableBelow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Left.
        /// </summary>
        public static string MiniToolBarInsertTableLeft
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTableLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Right.
        /// </summary>
        public static string MiniToolBarInsertTableRight
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTableRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        public static string MiniToolBarInsertTableToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarInsertTableToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string MiniToolBarItalicToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarItalicToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        public static string MiniToolBarNoColorHighlight
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNoColorHighlight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        public static string MiniToolBarNoHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNoHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MiniToolBarNoListToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNoListToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number Alignment: Left.
        /// </summary>
        public static string MiniToolBarNumberingAlignLeftToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNumberingAlignLeftToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number Alignment: Right.
        /// </summary>
        public static string MiniToolBarNumberingAlignRightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNumberingAlignRightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Numbering Library.
        /// </summary>
        public static string MiniToolBarNumberingHeader
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNumberingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        public static string MiniToolBarNumberingToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarNumberingToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string MiniToolBarPinkHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarPinkHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string MiniToolBarRedHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarRedHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string MiniToolBarTealHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarTealHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        public static string MiniToolBarTurquoiseHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarTurquoiseHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string MiniToolBarUnderlineToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarUnderlineToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string MiniToolBarVioletHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarVioletHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string MiniToolBarYellowHighlightToolTip
        {
            get
            {
                return ResourceManager.GetString("MiniToolBarYellowHighlightToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify
        {
            get
            {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modify Style.
        /// </summary>
        public static string ModifyStyleDialogTitle
        {
            get
            {
                return ResourceManager.GetString("ModifyStyleDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create New Style.
        /// </summary>
        public static string NewStyleDialogTitle
        {
            get
            {
                return ResourceManager.GetString("NewStyleDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberList
        {
            get
            {
                return ResourceManager.GetString("NumberList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string OptionPaneCloseButtonToolTip
        {
            get
            {
                return ResourceManager.GetString("OptionPaneCloseButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use search box for find text in the document..
        /// </summary>
        public static string OptionsPaneDescription
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        public static string OptionsPaneResultsHeader
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneResultsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string OptionsPaneSearch
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for..
        /// </summary>
        public static string OptionsPaneSearchErrorMessage
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use search box for find text in the document..
        /// </summary>
        public static string OptionsPaneSearchInformation
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to That&apos;s shows up a lot..
        /// </summary>
        public static string OptionsPaneSearchManyResultsInfo
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchManyResultsInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string OptionsPaneSearchNoResult
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchNoResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 result found.
        /// </summary>
        public static string OptionsPaneSearchOneResult
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchOneResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search paused.
        /// </summary>
        public static string OptionsPaneSearchPaused
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchPaused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result .
        /// </summary>
        public static string OptionsPaneSearchResult
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string OptionsPaneSearchResultOf
        {
            get
            {
                return ResourceManager.GetString("OptionsPaneSearchResultOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        public static string OrdinalList
        {
            get
            {
                return ResourceManager.GetString("OrdinalList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OrdinalText.
        /// </summary>
        public static string OrdinalTextList
        {
            get
            {
                return ResourceManager.GetString("OrdinalTextList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string ParagraphDialogAfterSpacing
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogAfterSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string ParagraphDialogAlignment
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string ParagraphDialogBeforeSpacing
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogBeforeSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string ParagraphDialogDirection
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First line.
        /// </summary>
        public static string ParagraphDialogFirstLineIndent
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogFirstLineIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ParagraphDialogGeneralHeader
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogGeneralHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hanging.
        /// </summary>
        public static string ParagraphDialogHangingIndent
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogHangingIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        public static string ParagraphDialogIndentHeader
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogIndentHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string ParagraphDialogLeftIndentValue
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogLeftIndentValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string ParagraphDialogLineSpacingAt
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogLineSpacingAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line Spacing.
        /// </summary>
        public static string ParagraphDialogLineSpacingType
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogLineSpacingType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string ParagraphDialogNoIndent
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogNoIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string ParagraphDialogRightIndent
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogRightIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string ParagraphDialogSpacingHeader
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogSpacingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string ParagraphDialogSpecialIndent
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogSpecialIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string ParagraphDialogSpecialIndentBy
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogSpecialIndentBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string ParagraphDialogTitle
        {
            get
            {
                return ResourceManager.GetString("ParagraphDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        public static string PasswordDialogEnterPassword
        {
            get
            {
                return ResourceManager.GetString("PasswordDialogEnterPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encrypt Document.
        /// </summary>
        public static string PasswordDialogTitle
        {
            get
            {
                return ResourceManager.GetString("PasswordDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent
        {
            get
            {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        public static string Pixel
        {
            get
            {
                return ResourceManager.GetString("Pixel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightAlignment
        {
            get
            {
                return ResourceManager.GetString("RightAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightMargin
        {
            get
            {
                return ResourceManager.GetString("RightMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row
        {
            get
            {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search for more things.
        /// </summary>
        public static string SearchButtonToolTip
        {
            get
            {
                return ResourceManager.GetString("SearchButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string SpecialList
        {
            get
            {
                return ResourceManager.GetString("SpecialList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SpellingPaneAddToDictionary
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneAddToDictionary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string SpellingPaneChange
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change All.
        /// </summary>
        public static string SpellingPaneChangeAll
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneChangeAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        public static string SpellingPaneIgnoreAll
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneIgnoreAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string SpellingPaneResume
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneResume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spelling.
        /// </summary>
        public static string SpellingPaneSpelling
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneSpelling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spelling check complete. You&apos;re good to go!.
        /// </summary>
        public static string SpellingPaneSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("SpellingPaneSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Style based on.
        /// </summary>
        public static string StyleDialogBasedOn
        {
            get
            {
                return ResourceManager.GetString("StyleDialogBasedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Style for following paragraph.
        /// </summary>
        public static string StyleDialogFollowingParagraph
        {
            get
            {
                return ResourceManager.GetString("StyleDialogFollowingParagraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string StyleDialogFormattingHeader
        {
            get
            {
                return ResourceManager.GetString("StyleDialogFormattingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string StyleDialogGeneralHeader
        {
            get
            {
                return ResourceManager.GetString("StyleDialogGeneralHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StyleDialogName
        {
            get
            {
                return ResourceManager.GetString("StyleDialogName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Style type.
        /// </summary>
        public static string StyleDialogStyleType
        {
            get
            {
                return ResourceManager.GetString("StyleDialogStyleType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string StylesDialogGeneralHeader
        {
            get
            {
                return ResourceManager.GetString("StylesDialogGeneralHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string StylesDialogTitle
        {
            get
            {
                return ResourceManager.GetString("StylesDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table
        {
            get
            {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string TableDialogAlignment
        {
            get
            {
                return ResourceManager.GetString("TableDialogAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow spacing between cells.
        /// </summary>
        public static string TableDialogAllowCellSpacing
        {
            get
            {
                return ResourceManager.GetString("TableDialogAllowCellSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow row to break across pages.
        /// </summary>
        public static string TableDialogAllowRowBreak
        {
            get
            {
                return ResourceManager.GetString("TableDialogAllowRowBreak", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell margins.
        /// </summary>
        public static string TableDialogCellMargin
        {
            get
            {
                return ResourceManager.GetString("TableDialogCellMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TableDialogCellOptions
        {
            get
            {
                return ResourceManager.GetString("TableDialogCellOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Column size.
        /// </summary>
        public static string TableDialogColumnSize
        {
            get
            {
                return ResourceManager.GetString("TableDialogColumnSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default cell margins.
        /// </summary>
        public static string TableDialogDefaultCellMargin
        {
            get
            {
                return ResourceManager.GetString("TableDialogDefaultCellMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default cell spacing.
        /// </summary>
        public static string TableDialogDefaultCellSpacing
        {
            get
            {
                return ResourceManager.GetString("TableDialogDefaultCellSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indent from Left.
        /// </summary>
        public static string TableDialogLeftIndent
        {
            get
            {
                return ResourceManager.GetString("TableDialogLeftIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Same as the whole table.
        /// </summary>
        public static string TableDialogMarginSameAsTable
        {
            get
            {
                return ResourceManager.GetString("TableDialogMarginSameAsTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preferred width.
        /// </summary>
        public static string TableDialogPreferredWidth
        {
            get
            {
                return ResourceManager.GetString("TableDialogPreferredWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Measure in.
        /// </summary>
        public static string TableDialogPreferredWidthType
        {
            get
            {
                return ResourceManager.GetString("TableDialogPreferredWidthType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat as header row at the top of each page.
        /// </summary>
        public static string TableDialogRepeatHeader
        {
            get
            {
                return ResourceManager.GetString("TableDialogRepeatHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string TableDialogRightAlignment
        {
            get
            {
                return ResourceManager.GetString("TableDialogRightAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indent from Right.
        /// </summary>
        public static string TableDialogRightIndent
        {
            get
            {
                return ResourceManager.GetString("TableDialogRightIndent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify height.
        /// </summary>
        public static string TableDialogRowHeight
        {
            get
            {
                return ResourceManager.GetString("TableDialogRowHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Row height is.
        /// </summary>
        public static string TableDialogRowHeightType
        {
            get
            {
                return ResourceManager.GetString("TableDialogRowHeightType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Row size.
        /// </summary>
        public static string TableDialogRowSize
        {
            get
            {
                return ResourceManager.GetString("TableDialogRowSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TableDialogSize
        {
            get
            {
                return ResourceManager.GetString("TableDialogSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table direction.
        /// </summary>
        public static string TableDialogTableDirection
        {
            get
            {
                return ResourceManager.GetString("TableDialogTableDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        public static string TableDialogTitle
        {
            get
            {
                return ResourceManager.GetString("TableDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vertical alignment.
        /// </summary>
        public static string TableDialogVerticalAlignment
        {
            get
            {
                return ResourceManager.GetString("TableDialogVerticalAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically resize to fit contents.
        /// </summary>
        public static string TableOptionsDialogAllowAutoFit
        {
            get
            {
                return ResourceManager.GetString("TableOptionsDialogAllowAutoFit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TableOptionsDialogOptions
        {
            get
            {
                return ResourceManager.GetString("TableOptionsDialogOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table Options.
        /// </summary>
        public static string TableOptionsDialogTitle
        {
            get
            {
                return ResourceManager.GetString("TableOptionsDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table Properties.
        /// </summary>
        public static string TablePropertiesDialogTitle
        {
            get
            {
                return ResourceManager.GetString("TablePropertiesDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopAlignment
        {
            get
            {
                return ResourceManager.GetString("TopAlignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopMargin
        {
            get
            {
                return ResourceManager.GetString("TopMargin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UpLetter.
        /// </summary>
        public static string UpLetterList
        {
            get
            {
                return ResourceManager.GetString("UpLetterList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UpRoman.
        /// </summary>
        public static string UpRomanList
        {
            get
            {
                return ResourceManager.GetString("UpRomanList", resourceCulture);
            }
        }
    }
}
