//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cletor.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cletor.Resources.Languages.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AffirmativeButtonText {
            get {
                return ResourceManager.GetString("AffirmativeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files (*.xml,*.docx,*.dotx,*.doc,*.dot,*.htm,*.html,*.rtf,*.txt,*.xaml,*.md)|*.xml;*.docx;*.dotx;*.doc;*.dot;*.htm;*.html;*.rtf;*.txt;*.xaml;*.md|Word XML Document (*.xml)|*.xml|Word Document (*.docx)|*.docx|Word Template (*.dotx)|*.dotx|Word 97 - 2003 Document (*.doc)|*.doc|Word 97 - 2003 Template (*.dot)|*.dot|Web Page (*.htm,*.html)|*.htm;*.html|Rich Text File (*.rtf)|*.rtf|Text File (*.txt)|*.txt|Xaml File (*.xaml)|*.xaml|Markdown File (*.md)|*.md.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word XML Document (*.xml)|*.xml|Word Document (*.docx)|*.docx|Word Template (*.dotx)|*.dotx|Word 97 - 2003 Document (*.doc)|*.doc|Word 97 - 2003 Template (*.dot)|*.dot|Web Page (*.htm,*.html)|*.htm;*.html|Rich Text File (*.rtf)|*.rtf|Text File (*.txt)|*.txt|Xaml File (*.xaml)|*.xaml|Markdown File (*.md)|*.md.
        /// </summary>
        public static string AllSupportedFilesSave {
            get {
                return ResourceManager.GetString("AllSupportedFilesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes before closing the app?.
        /// </summary>
        public static string ClosingWithoutSavingDialogMessage {
            get {
                return ResourceManager.GetString("ClosingWithoutSavingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        /// </summary>
        public static string ClosingWithoutSavingDialogTitle {
            get {
                return ResourceManager.GetString("ClosingWithoutSavingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string CommandHeaderAbout {
            get {
                return ResourceManager.GetString("CommandHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string CommandHeaderExit {
            get {
                return ResourceManager.GetString("CommandHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string CommandHeaderNew {
            get {
                return ResourceManager.GetString("CommandHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string CommandHeaderOpen {
            get {
                return ResourceManager.GetString("CommandHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string CommandHeaderPrint {
            get {
                return ResourceManager.GetString("CommandHeaderPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string CommandHeaderSave {
            get {
                return ResourceManager.GetString("CommandHeaderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotcuts.
        /// </summary>
        public static string CommandHeaderShortcuts {
            get {
                return ResourceManager.GetString("CommandHeaderShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays information about Clean Editor.
        /// </summary>
        public static string CommandToolTipAbout {
            get {
                return ResourceManager.GetString("CommandToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the application.
        /// </summary>
        public static string CommandToolTipExit {
            get {
                return ResourceManager.GetString("CommandToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new document.
        /// </summary>
        public static string CommandToolTipNew {
            get {
                return ResourceManager.GetString("CommandToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a document.
        /// </summary>
        public static string CommandToolTipOpen {
            get {
                return ResourceManager.GetString("CommandToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the document.
        /// </summary>
        public static string CommandToolTipPrint {
            get {
                return ResourceManager.GetString("CommandToolTipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves unsaved changes.
        /// </summary>
        public static string CommandToolTipSave {
            get {
                return ResourceManager.GetString("CommandToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the list of keyboard shortcuts.
        /// </summary>
        public static string CommandToolTipShortcuts {
            get {
                return ResourceManager.GetString("CommandToolTipShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document.
        /// </summary>
        public static string DefaultDocumentTitle {
            get {
                return ResourceManager.GetString("DefaultDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select temporal files path.
        /// </summary>
        public static string FolderPickerTitle {
            get {
                return ResourceManager.GetString("FolderPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Clean Editor.
        /// </summary>
        public static string LabelAboutTitle {
            get {
                return ResourceManager.GetString("LabelAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string LabelBold {
            get {
                return ResourceManager.GetString("LabelBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By:.
        /// </summary>
        public static string LabelCreatedBy {
            get {
                return ResourceManager.GetString("LabelCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        public static string LabelCreationDate {
            get {
                return ResourceManager.GetString("LabelCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent.
        /// </summary>
        public static string LabelDecreaseIndent {
            get {
                return ResourceManager.GetString("LabelDecreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers:.
        /// </summary>
        public static string LabelDevelopers {
            get {
                return ResourceManager.GetString("LabelDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string LabelExit {
            get {
                return ResourceManager.GetString("LabelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string LabelFind {
            get {
                return ResourceManager.GetString("LabelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string LabelFindAndReplace {
            get {
                return ResourceManager.GetString("LabelFindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family.
        /// </summary>
        public static string LabelFontFamily {
            get {
                return ResourceManager.GetString("LabelFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string LabelFontSize {
            get {
                return ResourceManager.GetString("LabelFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics and Tables.
        /// </summary>
        public static string LabelGraphicsAndTables {
            get {
                return ResourceManager.GetString("LabelGraphicsAndTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 1.
        /// </summary>
        public static string LabelHeader1 {
            get {
                return ResourceManager.GetString("LabelHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 2.
        /// </summary>
        public static string LabelHeader2 {
            get {
                return ResourceManager.GetString("LabelHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 3.
        /// </summary>
        public static string LabelHeader3 {
            get {
                return ResourceManager.GetString("LabelHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 4.
        /// </summary>
        public static string LabelHeader4 {
            get {
                return ResourceManager.GetString("LabelHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent.
        /// </summary>
        public static string LabelIncreaseIndent {
            get {
                return ResourceManager.GetString("LabelIncreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string LabelInformation {
            get {
                return ResourceManager.GetString("LabelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string LabelInsertImage {
            get {
                return ResourceManager.GetString("LabelInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Link.
        /// </summary>
        public static string LabelInsertLink {
            get {
                return ResourceManager.GetString("LabelInsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Quote.
        /// </summary>
        public static string LabelInsertQuote {
            get {
                return ResourceManager.GetString("LabelInsertQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Remote Image.
        /// </summary>
        public static string LabelInsertRemoteImage {
            get {
                return ResourceManager.GetString("LabelInsertRemoteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        public static string LabelInsertTable {
            get {
                return ResourceManager.GetString("LabelInsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert List.
        /// </summary>
        public static string LabelInsetList {
            get {
                return ResourceManager.GetString("LabelInsetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is full screen.
        /// </summary>
        public static string LabelIsFullScreen {
            get {
                return ResourceManager.GetString("LabelIsFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string LabelItalic {
            get {
                return ResourceManager.GetString("LabelItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries:.
        /// </summary>
        public static string LabelLibraries {
            get {
                return ResourceManager.GetString("LabelLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string LabelLicense {
            get {
                return ResourceManager.GetString("LabelLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses:.
        /// </summary>
        public static string LabelLicenses {
            get {
                return ResourceManager.GetString("LabelLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string LabelLists {
            get {
                return ResourceManager.GetString("LabelLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string LabelMenu {
            get {
                return ResourceManager.GetString("LabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string LabelNew {
            get {
                return ResourceManager.GetString("LabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string LabelNormal {
            get {
                return ResourceManager.GetString("LabelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string LabelOpen {
            get {
                return ResourceManager.GetString("LabelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LabelOptions {
            get {
                return ResourceManager.GetString("LabelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string LabelPrint {
            get {
                return ResourceManager.GetString("LabelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date:.
        /// </summary>
        public static string LabelPublishDate {
            get {
                return ResourceManager.GetString("LabelPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string LabelQueries {
            get {
                return ResourceManager.GetString("LabelQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string LabelRedo {
            get {
                return ResourceManager.GetString("LabelRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string LabelReferences {
            get {
                return ResourceManager.GetString("LabelReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mode.
        /// </summary>
        public static string LabelScreenMode {
            get {
                return ResourceManager.GetString("LabelScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut List.
        /// </summary>
        public static string LabelShortcutList {
            get {
                return ResourceManager.GetString("LabelShortcutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code:.
        /// </summary>
        public static string LabelSourceCode {
            get {
                return ResourceManager.GetString("LabelSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Check.
        /// </summary>
        public static string LabelSpellingCheck {
            get {
                return ResourceManager.GetString("LabelSpellingCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string LabelStrikeThrough {
            get {
                return ResourceManager.GetString("LabelStrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal files path.
        /// </summary>
        public static string LabelTemporalFilesPath {
            get {
                return ResourceManager.GetString("LabelTemporalFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terns of use:.
        /// </summary>
        public static string LabelTernsOfUse {
            get {
                return ResourceManager.GetString("LabelTernsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Format.
        /// </summary>
        public static string LabelTextFormat {
            get {
                return ResourceManager.GetString("LabelTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Styles.
        /// </summary>
        public static string LabelTextStyles {
            get {
                return ResourceManager.GetString("LabelTextStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen.
        /// </summary>
        public static string LabelToggleFullScreen {
            get {
                return ResourceManager.GetString("LabelToggleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Theme.
        /// </summary>
        public static string LabelToggleTheme {
            get {
                return ResourceManager.GetString("LabelToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string LabelUnderline {
            get {
                return ResourceManager.GetString("LabelUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string LabelUndo {
            get {
                return ResourceManager.GetString("LabelUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.0.1.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NegativeButtonText {
            get {
                return ResourceManager.GetString("NegativeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path.
        /// </summary>
        public static string OptionCurrentPath {
            get {
                return ResourceManager.GetString("OptionCurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Font family.
        /// </summary>
        public static string OptionSelectAFontFamily {
            get {
                return ResourceManager.GetString("OptionSelectAFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a font size (Min:8, Max:100).
        /// </summary>
        public static string OptionSelectAFontSize {
            get {
                return ResourceManager.GetString("OptionSelectAFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string OptionSelectALanguage {
            get {
                return ResourceManager.GetString("OptionSelectALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme.
        /// </summary>
        public static string OptionSelectATheme {
            get {
                return ResourceManager.GetString("OptionSelectATheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for changes....
        /// </summary>
        public static string ProcessMessageCheckingChanges {
            get {
                return ResourceManager.GetString("ProcessMessageCheckingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting the imgae....
        /// </summary>
        public static string ProcessMessageInsertingImage {
            get {
                return ResourceManager.GetString("ProcessMessageInsertingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ProcessMessageLoading {
            get {
                return ResourceManager.GetString("ProcessMessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening large document....
        /// </summary>
        public static string ProcessMessageOpening {
            get {
                return ResourceManager.GetString("ProcessMessageOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        public static string ProcessMessageSaving {
            get {
                return ResourceManager.GetString("ProcessMessageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold (Ctrl + B).
        /// </summary>
        public static string ToolTipBoldCommand {
            get {
                return ResourceManager.GetString("ToolTipBoldCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the temporal files location.
        /// </summary>
        public static string ToolTipChangeTemporalFilesCommand {
            get {
                return ResourceManager.GetString("ToolTipChangeTemporalFilesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme (F10).
        /// </summary>
        public static string ToolTipChangeTheme {
            get {
                return ResourceManager.GetString("ToolTipChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent (Ctrl + ,).
        /// </summary>
        public static string ToolTipDecreaseIndentCommand {
            get {
                return ResourceManager.GetString("ToolTipDecreaseIndentCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace (Ctrl + H).
        /// </summary>
        public static string ToolTipFindAndReplaceCommand {
            get {
                return ResourceManager.GetString("ToolTipFindAndReplaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl + F).
        /// </summary>
        public static string ToolTipFindCommand {
            get {
                return ResourceManager.GetString("ToolTipFindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent (Ctrl + M).
        /// </summary>
        public static string ToolTipIncreaseIndentCommand {
            get {
                return ResourceManager.GetString("ToolTipIncreaseIndentCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image (Ctrl + Shift + I).
        /// </summary>
        public static string ToolTipInsertImageCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertImageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Link (Ctrl + K).
        /// </summary>
        public static string ToolTipInsertLinkCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertLinkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert List (Ctrl + Alt + L).
        /// </summary>
        public static string ToolTipInsertListCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Quote (Ctrl + Q).
        /// </summary>
        public static string ToolTipInsertQuoteCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertQuoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Remote Image (Ctrl + Shift + R).
        /// </summary>
        public static string ToolTipInsertRemoteImageCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertRemoteImageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table (Ctrl + T).
        /// </summary>
        public static string ToolTipInsertTableCommand {
            get {
                return ResourceManager.GetString("ToolTipInsertTableCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic (Ctrl + I).
        /// </summary>
        public static string ToolTipItalicCommand {
            get {
                return ResourceManager.GetString("ToolTipItalicCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files management.
        /// </summary>
        public static string ToolTipMainMenu {
            get {
                return ResourceManager.GetString("ToolTipMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the list of styles.
        /// </summary>
        public static string ToolTipOpenStylesCommand {
            get {
                return ResourceManager.GetString("ToolTipOpenStylesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options (F9).
        /// </summary>
        public static string ToolTipOptions {
            get {
                return ResourceManager.GetString("ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the last operation.
        /// </summary>
        public static string ToolTipRedoMenu {
            get {
                return ResourceManager.GetString("ToolTipRedoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 1 (Ctrl + 1).
        /// </summary>
        public static string ToolTipSetHeader1StyleCommand {
            get {
                return ResourceManager.GetString("ToolTipSetHeader1StyleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 2 (Ctrl + 2).
        /// </summary>
        public static string ToolTipSetHeader2StyleCommand {
            get {
                return ResourceManager.GetString("ToolTipSetHeader2StyleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 3 (Ctrl + 3).
        /// </summary>
        public static string ToolTipSetHeader3StyleCommand {
            get {
                return ResourceManager.GetString("ToolTipSetHeader3StyleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header 4 (Ctrl + 4).
        /// </summary>
        public static string ToolTipSetHeader4StyleCommand {
            get {
                return ResourceManager.GetString("ToolTipSetHeader4StyleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal (Ctrl + 0).
        /// </summary>
        public static string ToolTipSetNormalStyleCommand {
            get {
                return ResourceManager.GetString("ToolTipSetNormalStyleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the spelling pane (F7).
        /// </summary>
        public static string ToolTipSpellCheckCommand {
            get {
                return ResourceManager.GetString("ToolTipSpellCheckCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough (Ctrl + Shift + S).
        /// </summary>
        public static string ToolTipStrikeThroughCommand {
            get {
                return ResourceManager.GetString("ToolTipStrikeThroughCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen (F11).
        /// </summary>
        public static string ToolTipToggleFullScreenMenu {
            get {
                return ResourceManager.GetString("ToolTipToggleFullScreenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle toolbar visibility mode.
        /// </summary>
        public static string ToolTipToggleToolbarModeCommand {
            get {
                return ResourceManager.GetString("ToolTipToggleToolbarModeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline (Ctrl + U).
        /// </summary>
        public static string ToolTipUnderlineCommand {
            get {
                return ResourceManager.GetString("ToolTipUnderlineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last operation (Ctrl + Z).
        /// </summary>
        public static string ToolTipUndoMenu {
            get {
                return ResourceManager.GetString("ToolTipUndoMenu", resourceCulture);
            }
        }
    }
}
